openapi: 3.0.3
info:
  title: Harness NextGen Software Delivery Platform API Reference
  version: '1.0'
  description: This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
  contact:
    email: contact@harness.io
servers:
  - url: 'http://app.harness.io'
    description: harness
tags:
  - name: Organization
    description: Everything about Organization
  - name: Project
    description: Everything about Project
paths:
  /v1/orgs:
    post:
      summary: Create Organization
      operationId: create-organization
      responses:
        '200':
          $ref: '#/components/responses/OrganizationResponse'
      description: Create a new Organization.
      security:
        - x-api-key: []
      tags:
        - Organization
      requestBody:
        $ref: '#/components/requestBodies/CreateOrganizationRequest'
      parameters:
        - $ref: '#/components/parameters/AccountQueryParam'
    get:
      summary: Get Organizations
      operationId: get-organizations
      responses:
        '200':
          $ref: '#/components/responses/OrganizationListResponse'
      description: Retrieve the information of the Organizations.
      security:
        - x-api-key: []
      tags:
        - Organization
      parameters:
        - $ref: '#/components/parameters/AccountQueryParam'
        - $ref: '#/components/parameters/OrgsQueryParam'
        - $ref: '#/components/parameters/SearchTerm'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Limit'
    parameters: []
  '/v1/orgs/{org}':
    parameters:
      - schema:
          type: string
        name: org
        in: path
        required: true
        description: Organization identifier
    get:
      summary: Get Organization
      responses:
        '200':
          $ref: '#/components/responses/OrganizationResponse'
      operationId: get-organization
      description: Retrieve the information of the organization with the matching organization identifier.
      security:
        - x-api-key: []
      tags:
        - Organization
      parameters:
        - $ref: '#/components/parameters/AccountQueryParam'
    put:
      summary: Update Organization
      operationId: update-organization
      responses:
        '200':
          $ref: '#/components/responses/OrganizationResponse'
      description: Update the information of the organization with the matching organization identifier.
      security:
        - x-api-key: []
      tags:
        - Organization
      requestBody:
        $ref: '#/components/requestBodies/UpdateOrganizationRequest'
      parameters:
        - $ref: '#/components/parameters/AccountQueryParam'
    delete:
      summary: Delete Organization
      operationId: delete-organization
      responses:
        '200':
          $ref: '#/components/responses/OrganizationResponse'
      description: Delete the information of the organization with the matching organization identifier.
      security:
        - x-api-key: []
      tags:
        - Organization
      parameters:
        - $ref: '#/components/parameters/AccountQueryParam'
  /v1/projects:
    post:
      summary: Create Project
      tags:
        - Project
      responses:
        '200':
          $ref: '#/components/responses/ProjectResponse'
      operationId: create-account-scoped-project
      security:
        - x-api-key: []
      description: Creates a new Project
      requestBody:
        $ref: '#/components/requestBodies/CreateProjectRequest'
      parameters:
        - $ref: '#/components/parameters/AccountQueryParam'
    get:
      summary: Get Projects
      tags:
        - Project
      responses:
        '200':
          $ref: '#/components/responses/ProjectListResponse'
      operationId: get-account-scoped-projects
      description: Retrieves the information of the Projects.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountQueryParam'
        - $ref: '#/components/parameters/OrgsQueryParam'
        - $ref: '#/components/parameters/ProjectsQueryParam'
        - schema:
            type: boolean
            default: true
          in: query
          name: has_module
          description: This boolean specifies whether to Filter Projects which has the Module of type passed in the moduleType parameter or not
        - schema:
            type: string
          in: query
          name: module_type
          description: Project's module type
        - $ref: '#/components/parameters/SearchTerm'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Limit'
    parameters: []
  '/v1/orgs/{org}/projects':
    post:
      summary: Create Project
      tags:
        - Project
      responses:
        '200':
          $ref: '#/components/responses/ProjectResponse'
      operationId: create-org-scoped-project
      security:
        - x-api-key: []
      description: Creates a new Project
      requestBody:
        $ref: '#/components/requestBodies/CreateProjectRequest'
      parameters:
        - $ref: '#/components/parameters/AccountQueryParam'
    get:
      summary: Get Projects
      tags:
        - Project
      responses:
        '200':
          $ref: '#/components/responses/ProjectListResponse'
      operationId: get-org-scoped-projects
      description: Retrieves the information of the Projects.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountQueryParam'
        - $ref: '#/components/parameters/ProjectsQueryParam'
        - schema:
            type: boolean
            default: true
          in: query
          name: has_module
          description: This boolean specifies whether to Filter Projects which has the Module of type passed in the moduleType parameter or not
        - schema:
            type: string
          in: query
          name: module_type
          description: Project's module type
        - $ref: '#/components/parameters/SearchTerm'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Limit'
    parameters:
      - $ref: '#/components/parameters/OrgPathParam'
  '/v1/projects/{project}':
    get:
      summary: Get Project
      tags:
        - Project
      responses:
        '200':
          $ref: '#/components/responses/ProjectResponse'
      operationId: get-account-scoped-project
      description: Retrieve the information of the Project with the matching Project identifier.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountQueryParam'
    put:
      summary: Update Project
      tags:
        - Project
      responses:
        '200':
          $ref: '#/components/responses/ProjectResponse'
      operationId: update-account-scoped-project
      description: Updates the information of the Project with the matching Project identifier.
      security:
        - x-api-key: []
      requestBody:
        $ref: '#/components/requestBodies/UpdateProjectRequest'
      parameters:
        - $ref: '#/components/parameters/AccountQueryParam'
    delete:
      summary: Delete Project
      tags:
        - Project
      responses:
        '200':
          $ref: '#/components/responses/ProjectResponse'
      operationId: delete-account-scoped-project
      description: Deletes the information of the Project with the matching Project identifier.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountQueryParam'
    parameters:
      - schema:
          type: string
        name: project
        in: path
        required: true
        description: Project identifier
  '/v1/orgs/{org}/projects/{project}':
    get:
      summary: Get Project
      tags:
        - Project
      responses:
        '200':
          $ref: '#/components/responses/ProjectResponse'
      operationId: get-org-scoped-project
      description: Retrieve the information of the Project with the matching Project identifier.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountQueryParam'
    put:
      summary: Update Project
      tags:
        - Project
      responses:
        '200':
          $ref: '#/components/responses/ProjectResponse'
      operationId: update-org-scoped-project
      description: Updates the information of the Project with the matching Project identifier.
      security:
        - x-api-key: []
      requestBody:
        $ref: '#/components/requestBodies/UpdateProjectRequest'
      parameters:
        - $ref: '#/components/parameters/AccountQueryParam'
    delete:
      summary: Delete Project
      tags:
        - Project
      responses:
        '200':
          $ref: '#/components/responses/ProjectResponse'
      operationId: delete-org-scoped-project
      description: Deletes the information of the Project with the matching Project identifier.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountQueryParam'
    parameters:
      - $ref: '#/components/parameters/OrgPathParam'
      - schema:
          type: string
        name: project
        in: path
        required: true
        description: Project identifier
components:
  schemas:
    CreateOrganizationRequest:
      description: Create Organization request
      type: object
      x-examples:
        example-1:
          slug: example_organization
          name: Example Organization
          description: This is an Example Organization
          tags:
            example-tag-1: example-tag-1-value
            example-tag-2: example-tag-2-value
      properties:
        slug:
          type: string
          minLength: 1
          pattern: '^[a-zA-Z_][0-9a-zA-Z_$]{0,63}$'
          description: Organization identifier
          maxLength: 64
        name:
          type: string
          minLength: 1
          pattern: '^[a-zA-Z_][0-9a-zA-Z-_ ]{0,63}$'
          description: Organization name
          maxLength: 64
        description:
          type: string
          maxLength: 1024
          description: Organization description
        tags:
          type: object
          additionalProperties:
            type: string
          maxProperties: 128
          description: Organization tags
      required:
        - slug
        - name
    ModuleType:
      type: string
      description: Type of Modules
      enum:
        - CD
        - CI
        - CV
        - CF
        - CE
        - STO
        - CORE
        - PMS
        - TEMPLATESERVICE
        - GOVERNANCE
    CreateProjectRequest:
      description: Create Project Request
      type: object
      x-examples:
        example-1:
          slug: example_project_identifier
          name: example-project-name
          color: '#0063F7'
          modules:
            - CD
          description: This is a example Project
          tags:
            property1: value1
            property2: value2
      properties:
        slug:
          type: string
          minLength: 1
          pattern: '^[a-zA-Z_][0-9a-zA-Z_$]{0,63}$'
          description: Project identifier
          maxLength: 64
        name:
          type: string
          minLength: 1
          pattern: '^[a-zA-Z_][0-9a-zA-Z-_ ]{0,63}$'
          description: Project name
          maxLength: 64
        color:
          type: string
          description: Project color
        modules:
          type: array
          maxItems: 1024
          description: List of modules for project
          items:
            $ref: '#/components/schemas/ModuleType'
        description:
          type: string
          maxLength: 1024
          description: Project description
        tags:
          type: object
          additionalProperties:
            type: string
          maxProperties: 128
          description: Project tags
      required:
        - slug
        - name
    ProjectResponse:
      description: Project Response model
      type: object
      x-examples:
        example-1:
          org: example_org_identifier
          slug: example_project_identifier
          name: example-project-name
          color: '#0063F7'
          modules:
            - CD
          description: This is a example Project
          tags:
            property1: value1
            property2: value2
          createdAt: 1234567890
          lastModifiedAt: 1234567890
      properties:
        created_at:
          type: integer
          format: int64
          description: Creation timestamp for the project
        last_modified_at:
          type: integer
          format: int64
          description: Last modification timestamp for the project
        org:
          type: string
          description: Organization identifier for the project
        slug:
          type: string
          description: Project identifier
        name:
          type: string
          description: Project name
        color:
          type: string
          description: Project color
        modules:
          type: array
          uniqueItems: true
          description: List of module for project
          items:
            $ref: '#/components/schemas/ModuleType'
        description:
          type: string
          description: Project description
        tags:
          type: object
          additionalProperties:
            type: string
          description: Project tags
    OrganizationResponse:
      title: OrganizationResponse
      type: object
      description: Organization Response Model
      x-examples:
        example-1:
          slug: example_organization
          name: Example Organization
          description: This is an Example Organization
          tags:
            example-tag-1: example-tag-1-value
            example-tag-2: example-tag-2-value
          created_at: 1234567890
          last_modified_at: 1234567890
          harness_managed: true
      properties:
        created_at:
          type: integer
          description: Creation timestamp for organization
          format: int64
        last_modified_at:
          type: integer
          format: int64
          description: Last modification timestamp for Organization
        harness_managed:
          type: boolean
          description: 'This indicates if this Organization is managed by Harness or not. If True, Harness can manage and modify this Organization.'
        slug:
          type: string
          description: Organization identifier
        name:
          type: string
          description: Organization name
        description:
          type: string
          description: Organization description
        tags:
          type: object
          additionalProperties:
            type: string
          description: Organization tags
    UpdateOrganizationRequest:
      description: Update Organization request
      type: object
      x-examples:
        example-1:
          name: Example Organization
          description: This is an Example Organization
          tags:
            example-tag-1: example-tag-1-value
            example-tag-2: example-tag-2-value
      properties:
        name:
          type: string
          minLength: 1
          pattern: '^[a-zA-Z_][0-9a-zA-Z-_ ]{0,63}$'
          description: 'Organization name '
          maxLength: 64
        description:
          type: string
          maxLength: 1024
          description: Organization description
        tags:
          type: object
          description: Organization tags
          additionalProperties:
            type: string
          maxProperties: 128
      required:
        - name
        - description
    UpdateProjectRequest:
      description: Update Project Request
      type: object
      x-examples:
        example-1:
          name: example-project-name
          color: '#0063F7'
          modules:
            - CD
          description: This is a example Project
          tags:
            property1: value1
            property2: value2
      properties:
        name:
          type: string
          minLength: 1
          pattern: '^[a-zA-Z_][0-9a-zA-Z-_ ]{0,63}$'
          maxLength: 64
          description: Project name
        color:
          type: string
          minLength: 1
          description: Project color
        modules:
          type: array
          maxItems: 1024
          description: List of modules for project
          items:
            $ref: '#/components/schemas/ModuleType'
        description:
          type: string
          minLength: 1
          maxLength: 1024
          description: Project description
        tags:
          type: object
          description: Project tags
          additionalProperties:
            type: string
          maxProperties: 128
      required:
        - name
  securitySchemes:
    x-api-key:
      name: x-api-key
      type: apiKey
      in: header
  responses:
    OrganizationResponse:
      description: Organization response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrganizationResponse'
          examples:
            example-organization-response:
              value:
                slug: example_organization
                name: Example Organization
                description: This is an Example Organization
                tags:
                  example-tag-1: example-tag-1-value
                  example-tag-2: example-tag-2-value
                created_at: 1234567890
                last_modified_at: 1234567890
                harness_managed: true
    ProjectResponse:
      description: Project response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProjectResponse'
          examples:
            example-project-response-json:
              value:
                org: example_org_identifier
                slug: example_project_identifier
                name: example-project-name
                color: '#0063F7'
                modules:
                  - CD
                description: This is a example Project
                tags:
                  property1: value1
                  property2: value2
                created_at: 1234567890
                last_modified_at: 1234567890
        application/yaml:
          schema:
            $ref: '#/components/schemas/ProjectResponse'
          examples:
            example-project-response-yaml:
              value: |
                org: example_org_identifier
                slug: example_project_identifier
                name: example-project-name
                color: '#0063F7'
                modules:
                  - CD
                description: This is a example Project
                tags:
                  property1: value1
                  property2: value2
                created_at: 1234567890
                last_modified_at: 1234567890
    ProjectListResponse:
      description: Project list response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ProjectResponse'
          examples:
            example-project-list-response:
              value:
                - org: example_org_identifier
                  slug: example_project_identifier
                  name: example-project-name
                  color: '#0063F7'
                  modules:
                    - CD
                  description: This is a example Project
                  tags:
                    property1: value1
                    property2: value2
                  created_at: 1234567890
                  last_modified_at: 1234567890
      headers:
        Link:
          schema:
            type: string
          description: 'Links to related resources, in the format defined by [RFC 5988](https://tools.ietf.org/html/rfc5988#section-5). This will include a link with relation type `next` to the next page, if there is a next page.Link'
          examples:
            sample:
              value: '</v1/projects?org=dummy-orgnization&page=2&limit=1>; rel="next", </v1/projects?org=dummy-orgnization&page=1&limit=1>; rel="self", </v1/projects?org=dummy-orgnization&page=0&limit=1>; rel="previous", '
    OrganizationListResponse:
      description: Organization list response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/OrganizationResponse'
          examples:
            example-organizations-list-response:
              value:
                - slug: example_organization
                  name: Example Organization
                  description: This is an Example Organization
                  tags:
                    example-tag-1: example-tag-1-value
                    example-tag-2: example-tag-2-value
                  created_at: 1234567890
                  last_modified_at: 1234567890
                  harness_managed: true
      headers:
        Link:
          schema:
            type: string
          description: 'Links to related resources, in the format defined by [RFC 5988](https://tools.ietf.org/html/rfc5988#section-5). This will include a link with relation type `next` to the next page, if there is a next page.'
          examples:
            sample:
              value: '</v1/orgs?page=2&limit=1>; rel="next", </v1/orgs?page=1&limit=1>; rel="self", </v1/orgs?page=0&limit=1>; rel="previous", '
  requestBodies:
    UpdateProjectRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateProjectRequest'
          examples:
            example-project-update-request-json:
              value:
                name: example-project-name
                color: '#0063F7'
                modules:
                  - CD
                description: This is a example Project
                tags:
                  property1: value1
                  property2: value2
      description: Put the necessary fields for the API to update a Project.
      required: true
    CreateOrganizationRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateOrganizationRequest'
          examples:
            example-create-organization-request-json:
              value:
                slug: example_organization
                name: Example Organization
                description: This is an Example Organization
                tags:
                  example-tag-1: example-tag-1-value
                  example-tag-2: example-tag-2-value
      description: Post the necessary fields for the API to create a Organization.
      required: true
    UpdateOrganizationRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateOrganizationRequest'
          examples:
            example-organization-update-request-json:
              value:
                name: Example Organization
                description: This is an Example Organization
                tags:
                  example-tag-1: example-tag-1-value
                  example-tag-2: example-tag-2-value
      description: Put the necessary fields for the API to update a Organization.
      required: true
    CreateProjectRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateProjectRequest'
          examples:
            example-create-project-request-json:
              value:
                slug: example_project_identifier
                name: example-project-name
                color: '#0063F7'
                modules:
                  - CD
                description: This is a example Project
                tags:
                  property1: value1
                  property2: value2
        application/yaml:
          schema:
            $ref: '#/components/schemas/CreateProjectRequest'
          examples:
            example-create-project-request-yaml:
              value: |
                slug: example_project_identifier
                name: example-project-name
                color: '#0063F7'
                modules:
                  - CD
                description: This is a example Project
                tags:
                  property1: value1
                  property2: value2
      description: Post the necessary fields for the API to create a Project.
      required: true
  parameters:
    Page:
      name: page
      in: query
      required: false
      schema:
        type: integer
        default: 0
      description: "Pagination page number strategy: Specify the page number within the paginated collection related to the number of items in each page\t"
    Limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        default: 30
      description: 'Pagination: Number of items to return'
    SearchTerm:
      name: search_term
      in: query
      required: false
      schema:
        type: string
      description: This would be used to filter resources having attributes matching with search term.
    OrgQueryParam:
      name: org
      in: query
      schema:
        type: string
        default: default
      description: Slug field of the organization the resource is scoped to
    AccountQueryParam:
      name: account
      in: query
      required: false
      schema:
        type: string
      description: Slug field of the account the resource is scoped to. This is required for Authorization method other than x-api-key header. If you are using x-api-key header this can be skipped.
    OrgsQueryParam:
      name: org
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
      description: Slug field of the organizations the resource is scoped to
    ProjectsQueryParam:
      name: project
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
      description: Slug field of the projects the resource is scoped to
    OrgPathParam:
      name: org
      in: path
      required: true
      schema:
        type: string
      description: Slug field of the organization the resource is scoped to
    ProjectPathParam:
      name: project
      in: path
      required: true
      schema:
        type: string
      description: Slug field of the project the resource is scoped to
