openapi: 3.0.3
x-stoplight:
  id: bfet7n314xd4i
info:
  title: Harness NextGen Software Delivery Platform API Reference
  version: '1.0'
  description: This is the Open Api Spec 3 for the Access Control Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
  contact:
    email: contact@harness.io
servers:
  - url: 'https://app.harness.io'
    description: Harness host URL.
tags:
  - name: Account Roles
    description: This contains APIs for Account-scoped Roles.
    x-displayName: 'Account Roles [Beta]'
  - name: Organization Roles
    description: This contains APIs for Organization-scoped Roles.
    x-displayName: 'Organization Roles [Beta]'
  - name: Project Roles
    description: This contains APIs for Project-scoped Roles.
    x-displayName: 'Project Roles [Beta]'
  - name: Account Role Assignments
    description: This contains APIs for Account-scoped Role Assignments.
    x-displayName: 'Account Role Assignments [Beta]'
  - name: Org Role Assignments
    description: This contains APIs for Organization-scoped Role Assignments.
    x-displayName: 'Organization Role Assignments [Beta]'
  - name: Project Role Assignments
    description: This contains APIs for Project-scoped Role Assignments.
    x-displayName: 'Project Role Assignments [Beta]'
paths:
  /v1/roles:
    parameters: []
    get:
      summary: List Roles
      operationId: list-roles-acc
      description: Returns a list of Roles present in the Account scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/SearchTerm'
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Order'
      responses:
        '200':
          $ref: '#/components/responses/RolesListResponse'
      tags:
        - Account Roles
    post:
      summary: Create a Role
      operationId: create-role-acc
      description: Creates a custom Role in the Account scope.
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/CreateRoleRequest'
      responses:
        '201':
          $ref: '#/components/responses/RoleResponse'
      security:
        - x-api-key: []
      tags:
        - Account Roles
  /v1/public-access/enable:
    parameters: []
    post:
      summary: Enable Public Access for a Resource
      operationId: enable-public-access
      description: Enable Public Access for a Resource
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/PublicAccessRequest'
      responses:
        '201':
          $ref: '#/components/responses/PublicAccessResponse'
      security:
        - x-api-key: []
      x-internal: false
      tags:
        - Public Access
  /v1/analyze-access-policies:
    parameters: []
    post:
      summary: Analyze access policies within account
      operationId: analyze-account-access-policies
      description: Analyze access policies within account
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Order'
      requestBody:
        $ref: '#/components/requestBodies/AccessPolicyAnalysisRequest'
      responses:
        '200':
          $ref: '#/components/responses/AccessPolicyAnalysisResponse'
      security:
        - x-api-key: []
      x-internal: false
      tags:
        - Analyze Account Access Policy
  '/v1/orgs/{org}/analyze-access-policies':
    parameters:
      - $ref: '#/components/parameters/OrgParam'
    post:
      summary: Analyze access policies within a organization
      operationId: analyze-org-access-policies
      description: Analyze access policies within a organization
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Order'
      requestBody:
        $ref: '#/components/requestBodies/AccessPolicyAnalysisRequest'
      responses:
        '200':
          $ref: '#/components/responses/AccessPolicyAnalysisResponse'
      security:
        - x-api-key: []
      x-internal: false
      tags:
        - Analyze Organization Access Policy
  '/v1/orgs/{org}/projects/{project}/analyze-access-policies':
    parameters:
      - name: org
        in: path
        required: true
        schema:
          type: string
        description: Organization identifier
      - $ref: '#/components/parameters/ProjectParam'
    post:
      summary: Analyze access policies within a project
      operationId: analyze-project-access-policies
      description: Analyze access policies within a project
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Order'
      requestBody:
        $ref: '#/components/requestBodies/AccessPolicyAnalysisRequest'
      responses:
        '200':
          $ref: '#/components/responses/AccessPolicyAnalysisResponse'
      security:
        - x-api-key: []
      x-internal: false
      tags:
        - Analyze Project Access Policy
  /v1/public-access/is-resource-public:
    parameters: []
    post:
      summary: Returns if a Resource is public or not
      operationId: is-resource-public
      description: 'Returns if a Resource is public or not '
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/PublicAccessRequest'
      responses:
        '200':
          $ref: '#/components/responses/PublicAccessResponse'
      security:
        - x-api-key: []
      tags:
        - Public Access
      x-internal: true
  /v1/public-access/check-public:
    parameters: []
    post:
      summary: Returns if a list of Resource is public or not
      operationId: check-public
      description: 'Returns if a list of Resources is public or not '
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/PublicAccessCheckRequest'
      responses:
        '200':
          $ref: '#/components/responses/PublicAccessCheckResponse'
      security:
        - x-api-key: []
      tags:
        - Public Access
      x-internal: true
  /v1/public-access/disable:
    parameters: []
    put:
      summary: Disable public access on a Resource
      operationId: disable-public-access
      responses:
        '200':
          $ref: '#/components/responses/PublicAccessResponse'
      description: Disable Public Access
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - schema:
            type: string
          in: query
          name: account
          description: Account Identifier
        - schema:
            type: string
          in: query
          name: org
          description: Organisation Identifier
        - schema:
            type: string
          in: query
          name: project
          description: Project Identifier
        - schema:
            type: string
          in: query
          name: resource_type
          description: Resource type
        - schema:
            type: string
          in: query
          name: resource_identifier
          description: Resource Identifier
      tags:
        - Public Access
      x-internal: true
  '/v1/roles/{role}':
    parameters:
      - $ref: '#/components/parameters/RoleParam'
    get:
      summary: Retrieve a Role
      responses:
        '200':
          $ref: '#/components/responses/RoleResponse'
      operationId: get-role-acc
      description: Retrieves a Role from Account scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - Account Roles
    put:
      summary: Update a Role
      operationId: update-role-acc
      responses:
        '200':
          $ref: '#/components/responses/RoleResponse'
      description: Updates a Role from Account scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/CreateRoleRequest'
      tags:
        - Account Roles
    delete:
      summary: Delete a Role
      operationId: delete-role-acc
      responses:
        '200':
          $ref: '#/components/responses/RoleResponse'
      description: Deletes a custom Role from Account scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - Account Roles
  '/v1/orgs/{org}/roles':
    parameters:
      - $ref: '#/components/parameters/OrgParam'
    get:
      summary: List Roles
      tags:
        - Organization Roles
      responses:
        '200':
          $ref: '#/components/responses/RolesListResponse'
      operationId: list-roles-org
      description: Returns a list of Roles present in the Organization scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/SearchTerm'
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Order'
    post:
      summary: Create a Role
      operationId: create-role-org
      responses:
        '201':
          $ref: '#/components/responses/RoleResponse'
      description: Creates a custom Role in the Organization scope.
      security:
        - x-api-key: []
      requestBody:
        $ref: '#/components/requestBodies/CreateRoleRequest'
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - Organization Roles
  '/v1/orgs/{org}/roles/{role}':
    parameters:
      - $ref: '#/components/parameters/OrgParam'
      - $ref: '#/components/parameters/RoleParam'
    get:
      summary: Retrieve a Role
      responses:
        '200':
          $ref: '#/components/responses/RoleResponse'
      operationId: get-role-org
      description: Retrieves a Role from Organization scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - Organization Roles
    put:
      summary: Update a Role
      operationId: update-role-org
      responses:
        '200':
          $ref: '#/components/responses/RoleResponse'
      description: Updates a Role from Organization scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/CreateRoleRequest'
      tags:
        - Organization Roles
    delete:
      summary: Delete a Role
      operationId: delete-role-org
      responses:
        '200':
          $ref: '#/components/responses/RoleResponse'
      description: Deletes a custom Role from Organization scope.
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      security:
        - x-api-key: []
      tags:
        - Organization Roles
  '/v1/orgs/{org}/projects/{project}/roles':
    parameters:
      - $ref: '#/components/parameters/OrgParam'
      - $ref: '#/components/parameters/ProjectParam'
    get:
      summary: List Roles
      responses:
        '200':
          $ref: '#/components/responses/RolesListResponse'
      operationId: list-roles-project
      description: Returns a list of Roles present in the Project scope.
      parameters:
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/SearchTerm'
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Order'
      security:
        - x-api-key: []
      tags:
        - Project Roles
    post:
      summary: Create a Role
      operationId: create-role-project
      responses:
        '201':
          $ref: '#/components/responses/RoleResponse'
      description: Creates a custom Role in the Project scope.
      security:
        - x-api-key: []
      requestBody:
        $ref: '#/components/requestBodies/CreateRoleRequest'
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - Project Roles
  '/v1/orgs/{org}/projects/{project}/roles/{role}':
    parameters:
      - $ref: '#/components/parameters/OrgParam'
      - $ref: '#/components/parameters/ProjectParam'
      - $ref: '#/components/parameters/RoleParam'
    get:
      summary: Retrieve a Role
      responses:
        '200':
          $ref: '#/components/responses/RoleResponse'
      operationId: get-role-project
      security:
        - x-api-key: []
      description: Retrieves a Role from Project scope.
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - Project Roles
    put:
      summary: Update a Role
      operationId: update-role-project
      responses:
        '200':
          $ref: '#/components/responses/RoleResponse'
      security:
        - x-api-key: []
      requestBody:
        $ref: '#/components/requestBodies/CreateRoleRequest'
      description: Updates a Role from Project scope.
      tags:
        - Project Roles
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
    delete:
      summary: Delete a Role
      operationId: delete-role-project
      responses:
        '200':
          $ref: '#/components/responses/RoleResponse'
      description: Deletes a custom Role from Project scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - Project Roles
  /v1/role-assignments:
    get:
      summary: List role assignments
      tags:
        - Account Role Assignments
      responses:
        '200':
          $ref: '#/components/responses/RoleAssignmentListResponse'
      operationId: get-account-scoped-role-assignments
      description: Retrieves the information of the role assignments
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Order'
      security:
        - x-api-key: []
    post:
      summary: Create a role assignment
      operationId: create-account-scoped-role-assignments
      responses:
        '201':
          $ref: '#/components/responses/RoleAssignmentResponse'
      description: Create a role assignment
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - Account Role Assignments
      requestBody:
        $ref: '#/components/requestBodies/RoleAssignmentRequest'
      security:
        - x-api-key: []
  '/v1/role-assignments/{role-assignment}':
    parameters:
      - schema:
          type: string
        name: role-assignment
        in: path
        required: true
        description: Role assignment identifier
    get:
      summary: Retrieve a role assignment
      tags:
        - Account Role Assignments
      responses:
        '200':
          $ref: '#/components/responses/RoleAssignmentResponse'
      operationId: get-account-scoped-role-assignment
      description: Retrieves the information of the role assignment with the matching role assignment identifier.
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      security:
        - x-api-key: []
    delete:
      summary: Delete a role assignment
      operationId: delete-account-scoped-role-assignment
      responses:
        '200':
          $ref: '#/components/responses/RoleAssignmentResponse'
      description: Deletes the information of the role assignment with the matching role assignment identifier.
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - Account Role Assignments
      security:
        - x-api-key: []
  '/v1/orgs/{org}/role-assignments':
    get:
      summary: List role assignments
      tags:
        - Org Role Assignments
      responses:
        '200':
          $ref: '#/components/responses/RoleAssignmentListResponse'
      operationId: get-org-scoped-role-assignments
      description: Retrieves the information of the role assignments
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Order'
      security:
        - x-api-key: []
    post:
      summary: Create a role assignment
      operationId: create-org-scoped-role-assignments
      responses:
        '201':
          $ref: '#/components/responses/RoleAssignmentResponse'
      description: Create a role assignment
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - Org Role Assignments
      requestBody:
        $ref: '#/components/requestBodies/RoleAssignmentRequest'
      security:
        - x-api-key: []
    parameters:
      - $ref: '#/components/parameters/OrgParam'
  '/v1/orgs/{org}/role-assignments/{role-assignment}':
    parameters:
      - schema:
          type: string
        name: role-assignment
        in: path
        required: true
        description: Role assignment identifier
      - $ref: '#/components/parameters/OrgParam'
    get:
      summary: Retrieve a role assignment
      tags:
        - Org Role Assignments
      responses:
        '200':
          $ref: '#/components/responses/RoleAssignmentResponse'
      operationId: get-org-scoped-role-assignment
      description: Retrieves the information of the role assignment with the matching role assignment identifier.
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      security:
        - x-api-key: []
    delete:
      summary: Delete a role assignment
      operationId: delete-org-scoped-role-assignment
      responses:
        '200':
          $ref: '#/components/responses/RoleAssignmentResponse'
      description: Deletes the information of the role assignment with the matching role assignment identifier.
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - Org Role Assignments
      security:
        - x-api-key: []
  '/v1/orgs/{org}/projects/{project}/role-assignments':
    get:
      summary: List role assignments
      tags:
        - Project Role Assignments
      responses:
        '200':
          $ref: '#/components/responses/RoleAssignmentListResponse'
      operationId: get-project-scoped-role-assignments
      description: Retrieves the information of the role assignments
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Order'
      security:
        - x-api-key: []
    post:
      summary: Create a role assignment
      operationId: create-project-scoped-role-assignments
      responses:
        '201':
          $ref: '#/components/responses/RoleAssignmentResponse'
      description: Create a role assignment
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - Project Role Assignments
      requestBody:
        $ref: '#/components/requestBodies/RoleAssignmentRequest'
      security:
        - x-api-key: []
    parameters:
      - $ref: '#/components/parameters/OrgParam'
      - $ref: '#/components/parameters/ProjectParam'
  '/v1/orgs/{org}/projects/{project}/role-assignments/{role-assignment}':
    parameters:
      - schema:
          type: string
        name: role-assignment
        in: path
        required: true
        description: Role assignment identifier
      - $ref: '#/components/parameters/OrgParam'
      - $ref: '#/components/parameters/ProjectParam'
    get:
      summary: Retrieve a role assignment
      tags:
        - Project Role Assignments
      responses:
        '200':
          $ref: '#/components/responses/RoleAssignmentResponse'
      operationId: get-project-scoped-role-assignment
      description: Retrieves the information of the role assignment with the matching role assignment identifier.
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      security:
        - x-api-key: []
    delete:
      summary: Delete a role assignment
      operationId: delete-project-scoped-role-assignment
      responses:
        '200':
          $ref: '#/components/responses/RoleAssignmentResponse'
      description: Deletes the information of the role assignment with the matching role assignment identifier.
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - Project Role Assignments
      security:
        - x-api-key: []
  /v1/role-assignments/count:
    get:
      summary: Get role assignments count for an account
      tags:
        - Account Role Assignments
      responses:
        '200':
          description: Role assignments count for the account.
          content:
            application/json:
              schema:
                type: integer
                format: int32
      operationId: get-role-assignments-count
      x-stoplight:
        id: 7roi0ybzyljem
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      description: Get role assignments count for an account.
      x-internal: true
      security:
        - x-api-key: [ ]
  /v1/roles/count:
    get:
      summary: Get roles count for an account
      tags:
        - Account Roles
      responses:
        '200':
          description: Roles count for the account.
          content:
            application/json:
              schema:
                type: integer
                format: int32
      operationId: get-roles-count
      x-stoplight:
        id: 7roi0ybzyljem
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      description: Get roles count for an account.
      x-internal: true
      security:
        - x-api-key: []
components:
  schemas:
    RolesResponse:
      title: RolesResponse
      x-stoplight:
        id: q6oq3jxkd2who
      type: object
      description: Role Response Model
      x-examples:
        example-role:
          identifier: example_role
          name: Example_Role
          permissions:
            - core_resource_view
          allowed_scope_levels:
            - account
          description: This is an Example Role
          tags:
            example-tag-1: example-tag-1-value
            example-tag-2: example-tag-2-value
          scope:
            account: sample_account
            org: sample_organization
            project: sample_project
          created: 1234567890
          updated: 1234567890
          harness_managed: true
      properties:
        identifier:
          type: string
          description: Role Identifier
          pattern: '^[a-zA-Z_][0-9a-zA-Z_$]{0,127}$'
          minLength: 1
          maxLength: 128
        name:
          type: string
          description: Role Name
          pattern: '^[a-zA-Z_][0-9a-zA-Z-_ ]{0,127}$'
          minLength: 1
          maxLength: 128
        permissions:
          type: array
          description: Permissions for this Role.
          uniqueItems: true
          items:
            type: string
        allowed_scope_levels:
          type: array
          description: The Scope levels at which this Role can be used.
          uniqueItems: true
          items:
            type: string
            enum:
              - account
              - organization
              - project
        description:
          type: string
          description: Role description
          maxLength: 1024
        tags:
          type: object
          additionalProperties:
            type: string
          description: Role tags
          maxProperties: 128
        scope:
          $ref: '#/components/schemas/RoleScope'
        created:
          type: integer
          description: Creation timestamp for Role.
          format: int64
        updated:
          type: integer
          description: Last modification timestamp for Role.
          format: int64
        harness_managed:
          type: boolean
          description: 'This indicates if this Role is managed by Harness or not. If true, Harness can manage and modify this Role.'
      required:
        - identifier
        - name
    CreateRoleRequest:
      title: CreateRoleRequest
      x-stoplight:
        id: z8g6ol73nsqjs
      type: object
      description: Role request body
      x-examples:
        role-request:
          identifier: example_role
          name: Example_Role
          permissions:
            - core_view
          description: This is an Example Role
          tags:
            example-tag-1: example-tag-1-value
            example-tag-2: example-tag-2-value
      properties:
        identifier:
          type: string
          minLength: 1
          maxLength: 128
          pattern: '^[a-zA-Z_][0-9a-zA-Z_$]{0,127}$'
          description: Role identifier
        name:
          type: string
          minLength: 1
          maxLength: 128
          pattern: '^[a-zA-Z_][0-9a-zA-Z-_ ]{0,127}$'
          description: Role name
        permissions:
          type: array
          uniqueItems: true
          description: List of the permission identifiers.
          items:
            type: string
        description:
          type: string
          maxLength: 1024
          description: Role description
        tags:
          type: object
          additionalProperties:
            type: string
          maxProperties: 128
          description: Role tags
      required:
        - identifier
        - name
    RoleScope:
      title: Scope
      x-stoplight:
        id: w8j3bc9323bxb
      type: object
      description: Scope of the Role
      properties:
        account:
          type: string
          description: Account identifier
        org:
          type: string
          description: Organization identifier
        project:
          type: string
          description: Project identifier
      x-examples:
        example-1:
          account: sample_account
          org: sample_organization
          project: sample_project
    RoleAssignment:
      title: RoleAssignment
      type: object
      description: Role assignment request model
      properties:
        identifier:
          type: string
          description: Role assignment identifier
        resource_group:
          type: string
          description: Resource group name
        role:
          type: string
          description: Role identifier
        roleReference:
          $ref: '#/components/schemas/RoleReference'
        principal:
          $ref: '#/components/schemas/Principal'
        disabled:
          type: boolean
          description: Role assignment is disabled or not
        managed:
          type: boolean
          description: Role assignment is managed or not
      required:
        - identifier
        - resource_group
        - role
        - principal
    Principal:
      title: Principal
      type: object
      description: Role assignment principal
      properties:
        scope_level:
          type: string
          description: Principal scope level
        identifier:
          type: string
          description: Principal identifier
        type:
          type: string
          enum:
            - USER
            - USER_GROUP
            - SERVICE_ACCOUNT
          description: Principal type
      required:
        - identifier
        - type
    RoleReference:
      title: RoleReference
      type: object
      description: Role referenced in role assignment
      properties:
        scope_level:
          type: string
          description: Role scope level
        identifier:
          type: string
          description: Role identifier
      required:
        - scope_level
        - identifier
    RoleAssignmentResponse:
      title: RoleAssignmentResponse
      type: object
      description: Role assignment response model
      properties:
        role-assignment:
          $ref: '#/components/schemas/RoleAssignment'
        created:
          type: integer
          description: Creation timestamp for Role.
          format: int64
        updated:
          type: integer
          description: Last modification timestamp for Role.
          format: int64
        harness_managed:
          type: boolean
          description: Is harness managed
    PublicAccessRequest:
      title: PublicAccessRequest
      x-stoplight:
        id: iwewenxaom066
      type: object
      description: Request to mark a resource as public
      properties:
        resource_identifier:
          type: string
          description: Identifier of the resource
        resource_type:
          type: string
          description: Type of the resource.
        resource_scope:
          $ref: '#/components/schemas/Scope'
      required:
        - resource_identifier
        - resource_type
        - resource_scope
    PublicAccessCheckRequest:
      title: PublicAccessCheckRequest
      type: object
      description: Request to check if given resources are public or not
      x-stoplight:
        id: 2fa1394cf970a
      properties:
        resource_identifiers:
          type: array
          description: List of resource identifiers
          items:
            type: string
        resource_type:
          type: string
          description: Type of the resource.
        resource_scope:
          $ref: '#/components/schemas/Scope'
      required:
        - resource_identifiers
        - resource_type
        - resource_scope
      x-examples:
        Example 1:
          resource_identifiers:
            - pipelineIdentifier1
            - pipelineIdentifier2
          resource_type: PIPELINE
          resource_scope:
            account: ACCOUNT_ID
            org: ORG_ID
            project: PROJECT_ID
    Scope:
      title: Scope
      x-stoplight:
        id: 5ozno3ho0k6r7
      type: object
      description: Scope of the Resource
      properties:
        account:
          type: string
          description: Account Identifier
        org:
          type: string
          description: Org Identifier
        project:
          type: string
          description: Project Identifier
      required:
        - account
    RoleRequest:
      title: RoleRequest
      x-stoplight:
        id: c3e929c83d0fd
      type: object
      x-internal: false
      description: Request to analyze policies based on Role details
      properties:
        identifier:
          type: string
          description: Role identifier
        scope_level:
          type: string
          description: 'Scope level at which role is defined. This can be from query scope level or parent scope level. '
    Resource:
      title: Resource
      x-stoplight:
        id: t79jjwaf9icna
      type: object
      description: Request to analyze access policies based on Resource details. Resource scope can be provided from query scope or its child scope
      x-internal: false
      properties:
        identifier:
          type: string
          description: Identifier of resource in given scope
        type:
          type: string
          description: Type of resource in a given scope
        attribute:
          type: object
          additionalProperties:
            type: string
          description: Resource attribute such as "type" in case of Environment or Connector
        scope:
          $ref: '#/components/schemas/Scope'
    ResourceGroupResponse:
      type: object
      x-examples:
        Example 1:
          identifier: string
          name: string
      x-internal: false
      title: ResourceGroupResponse
      description: Resource Group details which is assigned along with role to provide access on resources.
      properties:
        identifier:
          type: string
          description: Resource group identifier
        name:
          type: string
          description: Resource group name
    AccessPolicyAnalysisRequest:
      title: AccessPolicyAnalysisRequest
      x-stoplight:
        id: e3t22fn76ryz7
      type: object
      x-internal: false
      description: Input that accepts parameters based on which access policies will be queried within a given scope.
      x-tags:
        - AccessPolicy
      properties:
        query_scope:
          $ref: '#/components/schemas/QueryScopeRequest'
        principal:
          $ref: '#/components/schemas/Principal'
        permission_identifier:
          type: string
          description: Permission identifier for which access policies need to be analysed.
        resource_group_identifier:
          type: string
          description: Resource group identifiert for which access policies need to be analysed.
        role:
          $ref: '#/components/schemas/RoleRequest'
        resource:
          $ref: '#/components/schemas/Resource'
        advance_options:
          $ref: '#/components/schemas/AccessAnalysisAdvanceOptions'
    AccessPolicyAnalysisResponse:
      title: AccessPolicyAnalysisResponse
      x-stoplight:
        id: z0jvavfz25ak4
      type: object
      x-internal: false
      description: Response that list parameters related to access policy and what type of access it provides and to which Principal.
      properties:
        role_assignment:
          $ref: '#/components/schemas/RoleAssignmentMetaData'
        principal:
          $ref: '#/components/schemas/PrincipalResponse'
        resource_group:
          $ref: '#/components/schemas/ResourceGroupResponse'
        role:
          $ref: '#/components/schemas/RoleResponse'
        permission:
          $ref: '#/components/schemas/Permission'
        resource:
          $ref: '#/components/schemas/Resource'
    PrincipalResponse:
      title: PrincipalResponse
      x-stoplight:
        id: 673d44eaneumv
      type: object
      description: Principal for which role assignment is created
      x-internal: false
      properties:
        identifier:
          type: string
          description: Principal Identifier
        name:
          type: string
          description: Principal Name
        type:
          type: string
          description: Principal type
        scope_level:
          type: string
          description: Scope of Principal
      required:
        - identifier
        - type
    AccessAnalysisAdvanceOptions:
      title: AccessAnalysisAdvanceOptions
      x-stoplight:
        id: xlq5y89mztz6k
      type: object
      description: Advance Options to control the output of a given query
      x-internal: false
      properties:
        expand_role:
          type: boolean
          description: 'True, if response should list all permissions inside role.'
          default: false
        expand_resource_group:
          type: boolean
          description: 'True, if response should list all resources inside a resource group.'
          default: false
        expand_user_group:
          type: boolean
          description: 'True, if response should list all users inside a user group.'
          default: false
    AccessPolicyAnalysisResponseWrapper:
      title: AccessPolicyAnalysisResponseWrapper
      x-stoplight:
        id: avjt5ezdvhxfb
      type: object
      description: This is the view of output for policy analyzer query.
      x-internal: false
      properties:
        access_policy_analysis_response:
          type: array
          items:
            $ref: '#/components/schemas/AccessPolicyAnalysisResponse'
    RoleAssignmentMetaData:
      title: RoleAssignmentMetaData
      x-stoplight:
        id: 9cdu46qqlkjov
      type: object
      x-internal: false
      properties:
        scope:
          $ref: '#/components/schemas/Scope'
        role_assignment_id:
          type: string
          description: Role assignment Identifier
        principal:
          $ref: '#/components/schemas/PrincipalResponse'
      required:
        - scope
        - role_assignment_id
      description: This contains Role Assignment details and to which Principal this Role Assignment is assigned.
    Permission:
      title: Permission
      x-stoplight:
        id: b1o4qt6tco3qj
      type: object
      x-internal: false
      description: Permission details which are assigned via given role assignment
      properties:
        identifier:
          type: string
          description: Permisision identifier
        name:
          type: string
          description: Permission Name
    QueryScopeRequest:
      title: QueryScopeRequest
      x-stoplight:
        id: 66hcxma97s02d
      type: object
      description: This includes details about the scope for which policies should be analysed
      x-internal: false
      properties:
        filter:
          type: string
          enum:
            - INCLUDING_CHILD_SCOPE
            - EXCLUDING_CHILD_SCOPE
          default: EXCLUDING_CHILD_SCOPE
          description: Filter provide a way of either selecting ONLY specified scope or also include its child scopes.
        scope:
          $ref: '#/components/schemas/Scope'
        include_access_policies_from_parent_scope:
          type: boolean
          default: false
    PublicAccessCheckResponse:
      title: PublicAccessCheckResponse
      x-stoplight:
        id: fh5hfwc6y1u7p
      type: object
      description: This contains list of resources along with information if they are public or not
      properties:
        resource_type:
          type: string
          description: Resource Type
        resource_scope:
          $ref: '#/components/schemas/Scope'
        public_access_list:
          type: array
          items:
            $ref: '#/components/schemas/PublicAccessListResponse'
      x-examples:
        Example 1:
          resource_type: PIPELINE
          resource_scope:
            account: ACCOUNT_ID
            org: ORG_ID
            project: PROJECT_ID
          public_access_list:
            - resource_identifier: pipelineIdentifier1
              public: true
            - resource_identifier: pipelineIdentifier2
              public: false
    PublicAccessListResponse:
      title: PublicAccessListResponse
      x-stoplight:
        id: 8mepgxbhco75c
      type: object
      properties:
        resource_identifier:
          type: string
          description: Identifier of a resource
        public:
          type: boolean
          description: 'If true, then resource is marked for public access'
    RoleResponse:
      title: RoleResponse
      x-stoplight:
        id: 1bd6pmusgc535
      type: object
      description: Role details
      properties:
        identifier:
          type: string
          description: Role Identifier
        name:
          type: string
          description: Role Name
        scope_level:
          type: string
          description: Scope at which Role is created
      x-internal: false
  securitySchemes:
    x-api-key:
      name: x-api-key
      type: apiKey
      in: header
      description: API key is a token provided while making the API calls. This is used to authenticate the client at the exposed endpoint.
  parameters:
    Limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        default: 30
        maximum: 100
      description: 'Pagination: Number of items to return.'
    Sort:
      name: sort
      in: query
      required: false
      schema:
        type: string
        enum:
          - identifier
          - name
          - created
          - updated
      description: Parameter on the basis of which sorting is done.
    Order:
      name: order
      in: query
      required: false
      schema:
        type: string
        enum:
          - ASC
          - DESC
      description: Order on the basis of which sorting is done.
    PageIndex:
      name: page
      in: query
      required: false
      schema:
        type: integer
        default: 0
      description: 'Pagination page number strategy: Specify the page number within the paginated collection related to the number of items on each page.'
    SearchTerm:
      name: search_term
      in: query
      required: false
      schema:
        type: string
      description: This would be used to filter resources having attributes matching the search term.
    OrgParam:
      name: org
      in: path
      required: true
      schema:
        type: string
      description: Organization identifier
    ProjectParam:
      name: project
      in: path
      required: true
      schema:
        type: string
      description: Project identifier
    RoleParam:
      name: role
      in: path
      required: true
      schema:
        type: string
      description: Role identifier
    AccountHeader:
      name: Harness-Account
      in: header
      required: false
      schema:
        type: string
      description: 'Identifier field of the account the resource is scoped to. This is required for Authorization methods other than the x-api-key header. If you are using the x-api-key header, this can be skipped.'
  responses:
    RolesListResponse:
      description: Roles List Response body
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/RolesResponse'
          examples:
            role-list-response:
              value:
                - identifier: example_role
                  name: Example_Role
                  permissions:
                    - core_resource_view
                  allowed_scope_levels:
                    - account
                  description: This is an Example Role
                  tags:
                    example-tag-1: example-tag-1-value
                    example-tag-2: example-tag-2-value
                  scope:
                    account: sample_account
                    org: sample_organization
                    project: sample_project
                  created: 1234567890
                  updated: 1234567890
                  harness_managed: true
        application/yaml:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/RolesResponse'
          examples:
            role-list-response:
              value: |
                - identifier: example_role
                  name: Example_Role
                  permissions:
                    - core_resource_view
                  allowed_scope_levels:
                    - account
                  description: This is an Example Role
                  tags:
                    example-tag-1: example-tag-1-value
                    example-tag-2: example-tag-2-value
                  scope:
                    account: sample_account
                    org: sample_organization
                    project: sample_project
                  created: 1234567890
                  updated: 1234567890
                  harness_managed: true
      headers:
        X-Total-Elements:
          schema:
            type: integer
          description: Total number of elements returned in Paginated response.
        X-Page-Number:
          schema:
            type: integer
          description: Page number in Paginated response.
        X-Page-Size:
          schema:
            type: integer
          description: Maximum page size in Paginated response.
    RoleResponse:
      description: Role Response body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RolesResponse'
          examples:
            role-response:
              value:
                identifier: example_role
                name: Example_Role
                permissions:
                  - core_resource_view
                allowed_scope_levels:
                  - account
                description: This is an Example Role
                tags:
                  example-tag-1: example-tag-1-value
                  example-tag-2: example-tag-2-value
                scope:
                  account: sample_account
                  org: sample_organization
                  project: sample_project
                created: 1234567890
                updated: 1234567890
                harness_managed: true
        application/yaml:
          schema:
            $ref: '#/components/schemas/RolesResponse'
          examples:
            role-response:
              value: |
                identifier: example_role
                name: Example_Role
                permissions:
                  - core_resource_view
                allowed_scope_levels:
                  - account
                description: This is an Example Role
                tags:
                  example-tag-1: example-tag-1-value
                  example-tag-2: example-tag-2-value
                scope:
                  account: sample_account
                  org: sample_organization
                  project: sample_project
                created: 1234567890
                updated: 1234567890
                harness_managed: true
    RoleAssignmentResponse:
      description: Role assignment response body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RoleAssignmentResponse'
          examples:
            role-assignment-response-json:
              value:
                role-assignment:
                  identifier: example_role_assignment
                  resource_group: example_resource_group_identifier
                  role: example_role_identifier
                  principal:
                    scope: ACCOUNT
                    identifier: example_principal_identifier
                    type: USER
                  disabled: false
                  managed: false
                created: 1234567890
                updated: 1234567890
                harness_managaed: false
        application/yaml:
          schema:
            $ref: '#/components/schemas/RoleAssignmentResponse'
          examples:
            role-assignment-response-yaml:
              value: |
                role-assignment:
                  identifier: example_role_assignment
                  resource_group: example_resource_group_identifier
                  role: example_role_identifier
                  principal:
                    scope: ACCOUNT
                    identifier: example_principal_identifier
                    type: USER
                  disabled: false
                  managed: false
                created: 1234567890
                updated: 1234567890
                harness_managaed: false
    RoleAssignmentListResponse:
      description: Role Assignment List Response body
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/RoleAssignmentResponse'
          examples:
            role-assignment-response-json:
              value:
                - role-assignment:
                    identifier: example_role_assignment
                    resource_group: example_resource_group_identifier
                    role: example_role_identifier
                    principal:
                      scope: ACCOUNT
                      identifier: example_principal_identifier
                      type: USER
                    disabled: false
                    managed: false
                  created: 1234567890
                  updated: 1234567890
                  harness_managaed: false
        application/yaml:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/RoleAssignmentResponse'
          examples:
            role-assignment-response-json:
              value: |
                - role-assignment:
                    identifier: example_role_assignment
                    resource_group: example_resource_group_identifier
                    role: example_role_identifier
                    principal:
                      scope: ACCOUNT
                      identifier: example_principal_identifier
                      type: USER
                    disabled: false
                    managed: false
                  created: 1234567890
                  updated: 1234567890
                  harness_managaed: false
      headers:
        X-Total-Elements:
          schema:
            type: integer
          description: Total number of elements returned in Paginated response.
        X-Page-Number:
          schema:
            type: integer
          description: Page number in Paginated response.
        X-Page-Size:
          schema:
            type: integer
          description: Maximum page size in Paginated response.
    PublicAccessResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: boolean
    AccessPolicyAnalysisResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccessPolicyAnalysisResponseWrapper'
      headers:
        X-Total-Elements:
          schema:
            type: integer
          description: Total number of elements returned in Paginated response.
        X-Page-Number:
          schema:
            type: integer
          description: Page number in Paginated response.
        X-Page-Size:
          schema:
            type: integer
          description: Maximum page size in Paginated response.
    PublicAccessCheckResponse:
      description: This returns if a list of resource identifiers is public or not.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PublicAccessCheckResponse'
  requestBodies:
    CreateRoleRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateRoleRequest'
          examples:
            role-request:
              value:
                identifier: example_role
                name: Example_Role
                permissions:
                  - core_view
                description: This is an Example Role
                tags:
                  example-tag-1: example-tag-1-value
                  example-tag-2: example-tag-2-value
        application/yaml:
          schema:
            $ref: '#/components/schemas/CreateRoleRequest'
          examples:
            role-request:
              value: |
                identifier: example_role
                name: Example_Role
                permissions:
                  - core_view
                description: This is an Example Role
                tags:
                  example-tag-1: example-tag-1-value
                  example-tag-2: example-tag-2-value
      description: Role Request body
      required: true
    RoleAssignmentRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RoleAssignment'
          examples:
            role-assignment-request-json:
              value:
                identifier: example_role_assignment
                resource_group: example_resource_group_identifier
                role: example_role_identifier
                principal:
                  scope: ACCOUNT
                  identifier: example_principal_identifier
                  type: USER
                disabled: false
                managed: false
        application/yaml:
          schema:
            $ref: '#/components/schemas/RoleAssignment'
          examples:
            role-assignment-request-yaml:
              value: |
                identifier: example_role_assignment
                resource_group: example_resource_group_identifier
                role: example_role_identifier
                principal:
                  scope: ACCOUNT
                  identifier: example_principal_identifier
                  type: USER
                disabled: false
                managed: false
      description: Role Request body
      required: true
    PublicAccessRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PublicAccessRequest'
    AccessPolicyAnalysisRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccessPolicyAnalysisRequest'
      description: This is the request body that accepts parameters based on which access policies will be analysed
    PublicAccessCheckRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PublicAccessCheckRequest'
      description: Request to query if given resources are public or not