openapi: 3.0.3
x-stoplight:
  id: bfet7n314xd4i
info:
  title: Harness NextGen Software Delivery Platform API Reference
  version: '1.0'
  description: This is the Open Api Spec 3 for the Platform Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
  contact:
    email: contact@harness.io
servers:
  - url: 'http://app.harness.io'
    description: localhost
tags:
  - name: Account Resource Groups
    description: This contains APIs for performing CRUD operations on Account level Resource Groups.
  - name: Organization Resource Groups
    description: This contains APIs for performing CRUD operations on Organization level Resource Groups.
  - name: Project Resource Groups
    description: This contains APIs for performing CRUD operations on Project level Resource Groups.
x-tagGroups:
  - name: Resource Groups
    tags:
      - Account Resource Groups
      - Organization Resource Groups
      - Project Resource Groups
paths:
  /v1/resource-groups:
    parameters: []
    get:
      summary: List Resource Groups
      operationId: list-resource-groups-acc
      description: Returns a list of Resource Groups present in the Account scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountParam'
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/SearchTerm'
        - $ref: '#/components/parameters/IdentifierFilter'
        - $ref: '#/components/parameters/ResourceListFilter'
        - $ref: '#/components/parameters/ManagedFilter'
      responses:
        '200':
          $ref: '#/components/responses/ResourceGroupsListResponse'
      tags:
        - Account Resource Groups
    post:
      summary: Create a Resource Group
      operationId: create-resource-group-acc
      description: Creates a custom Resource Group in the Account scope.
      parameters:
        - $ref: '#/components/parameters/AccountParam'
      security:
        - x-api-key: []
      tags:
        - Account Resource Groups
      requestBody:
        $ref: '#/components/requestBodies/CreateResourceGroupRequest'
      responses:
        '200':
          $ref: '#/components/responses/ResourceGroupsResponse'
  '/v1/resource-groups/{resource-group}':
    parameters:
      - $ref: '#/components/parameters/ResourceGroupParam'
    get:
      summary: Retrieve a Resource Group
      operationId: get-resource-group-acc
      description: Retrieves a Resource Group from Account scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountParam'
      tags:
        - Account Resource Groups
      responses:
        '200':
          $ref: '#/components/responses/ResourceGroupsResponse'
      x-internal: false
    put:
      summary: Update a Resource Group
      operationId: update-resource-group-acc
      responses:
        '200':
          $ref: '#/components/responses/ResourceGroupsResponse'
      description: Updates a Resource Group from Account scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountParam'
      tags:
        - Account Resource Groups
      requestBody:
        $ref: '#/components/requestBodies/CreateResourceGroupRequest'
    delete:
      summary: Delete a Resource Group
      operationId: delete-resource-group-acc
      responses:
        '200':
          $ref: '#/components/responses/ResourceGroupsResponse'
      description: Deletes a custom Resource Group from Account scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountParam'
      tags:
        - Account Resource Groups
  '/v1/orgs/{org}/resource-groups':
    parameters:
      - $ref: '#/components/parameters/OrgParam'
    get:
      summary: List Resource Groups
      tags:
        - Organization Resource Groups
      responses:
        '200':
          $ref: '#/components/responses/ResourceGroupsListResponse'
      operationId: list-resource-groups-org
      description: Returns a list of Resource Groups present in the Organization scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountParam'
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/SearchTerm'
        - $ref: '#/components/parameters/IdentifierFilter'
        - $ref: '#/components/parameters/ResourceListFilter'
        - $ref: '#/components/parameters/ManagedFilter'
    post:
      summary: Create a Resource Group
      operationId: create-resource-group-org
      description: Creates a custom Resource Group in the Organization scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountParam'
      tags:
        - Organization Resource Groups
      requestBody:
        $ref: '#/components/requestBodies/CreateResourceGroupRequest'
      responses:
        '200':
          $ref: '#/components/responses/ResourceGroupsResponse'
  '/v1/orgs/{org}/resource-groups/{resource-group}':
    parameters:
      - $ref: '#/components/parameters/OrgParam'
      - $ref: '#/components/parameters/ResourceGroupParam'
    get:
      summary: Retrieve a Resource Group
      operationId: get-resource-group-org
      description: Retrieves a Resource Group from Organization scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountParam'
      tags:
        - Organization Resource Groups
      responses:
        '200':
          $ref: '#/components/responses/ResourceGroupsResponse'
    put:
      summary: Update a Resource Group
      operationId: update-resource-group-org
      responses:
        '200':
          $ref: '#/components/responses/ResourceGroupsResponse'
      description: Updates a Resource Group from Organization scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountParam'
      requestBody:
        $ref: '#/components/requestBodies/CreateResourceGroupRequest'
      tags:
        - Organization Resource Groups
    delete:
      summary: Delete a Resource Group
      operationId: delete-resource-group-org
      responses:
        '200':
          $ref: '#/components/responses/ResourceGroupsResponse'
      description: Deletes a custom Resource Group from Organization scope.
      parameters:
        - $ref: '#/components/parameters/AccountParam'
      security:
        - x-api-key: []
      tags:
        - Organization Resource Groups
  '/v1/orgs/{org}/projects/{project}/resource-groups':
    parameters:
      - name: org
        in: path
        required: true
        schema:
          type: string
        description: Organization identifier
      - name: project
        in: path
        required: true
        schema:
          type: string
        description: Project identifier
    get:
      summary: List Resource Groups
      responses:
        '200':
          $ref: '#/components/responses/ResourceGroupsListResponse'
      operationId: list-resource-groups-project
      description: Returns a list of Resource Groups present in the Project scope.
      parameters:
        - $ref: '#/components/parameters/AccountParam'
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/SearchTerm'
        - $ref: '#/components/parameters/IdentifierFilter'
        - $ref: '#/components/parameters/ResourceListFilter'
        - $ref: '#/components/parameters/ManagedFilter'
      security:
        - x-api-key: []
      tags:
        - Project Resource Groups
    post:
      summary: Create a Resource Group
      operationId: create-resource-group-project
      description: Creates a custom Resource Group in the Project scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountParam'
      tags:
        - Project Resource Groups
      requestBody:
        $ref: '#/components/requestBodies/CreateResourceGroupRequest'
      responses:
        '200':
          $ref: '#/components/responses/ResourceGroupsResponse'
  '/v1/orgs/{org}/projects/{project}/resource-groups/{resource-group}':
    parameters:
      - $ref: '#/components/parameters/OrgParam'
      - $ref: '#/components/parameters/ProjectParam'
      - $ref: '#/components/parameters/ResourceGroupParam'
    get:
      summary: Retrieve a Resource Group
      operationId: get-resource-group-project
      security:
        - x-api-key: []
      description: Retrieves a Resource Group from Project scope.
      parameters:
        - $ref: '#/components/parameters/AccountParam'
      tags:
        - Project Resource Groups
      responses:
        '200':
          $ref: '#/components/responses/ResourceGroupsResponse'
    put:
      summary: Update a Resource Group
      operationId: update-resource-group-project
      responses:
        '200':
          $ref: '#/components/responses/ResourceGroupsResponse'
      security:
        - x-api-key: []
      requestBody:
        $ref: '#/components/requestBodies/CreateResourceGroupRequest'
      description: Updates a Resource Group from Project scope.
      tags:
        - Project Resource Groups
      parameters:
        - $ref: '#/components/parameters/AccountParam'
    delete:
      summary: Delete a Resource Group
      operationId: delete-resource-group-project
      responses:
        '200':
          $ref: '#/components/responses/ResourceGroupsResponse'
      description: Deletes a custom Resource Group from Project scope.
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountParam'
      tags:
        - Project Resource Groups
components:
  schemas:
    ResourceGroupsResponse:
      title: Resource Groups Response
      x-stoplight:
        id: q6oq3jxkd2who
      type: object
      description: Resource Group Response Model
      x-examples:
        example-resource-group:
          slug: example_resource_group
          name: Example_Resource Group
          color: '#0063F7'
          tags:
            example-tag-1: example-tag-1-value
            example-tag-2: example-tag-2-value
          description: This is an Example Resource Group
          allowed_scope_levels:
            - account
          included_scope:
            - filter: EXCLUDING_CHILD_SCOPES
              account: sample_account
              org: sample_organization
              project: sample_project
          resource_filter:
            - resource_type: resource
              identifiers:
                - example_resource
              attribute_name: resource_attribute
              attribute_values:
                - example_resource_attribute
          include_all: false
          harness_managed: true
          created: 1234567890
          updated: 1234567890
      properties:
        slug:
          type: string
          description: Resource Group Identifier
        name:
          type: string
          description: Resource Group Name
        color:
          type: string
          description: Color associated with the Resource Group.
        tags:
          type: object
          additionalProperties:
            type: string
          description: Resource Group tags
        description:
          type: string
          description: Resource Group description
        allowed_scope_levels:
          type: array
          description: List of allowed scope levels for this Resource Group.
          uniqueItems: true
          items:
            type: string
            enum:
              - account
              - organization
              - project
        included_scope:
          type: array
          description: Scopes included in the Resource Group.
          items:
            $ref: '#/components/schemas/ResourceGroupScope'
        resource_filter:
          type: array
          description: Contains Resource filter for a Resource Group.
          items:
            $ref: '#/components/schemas/ResourceFilter'
        include_all:
          type: boolean
          description: Boolean value for including all resources in Resource Group.
        harness_managed:
          type: boolean
          description: 'This indicates if this Resource Group is managed by Harness or not. If true, Harness can manage and modify this Resource Group.'
        created:
          type: integer
          description: Creation timestamp for Resource Group.
          format: int64
        updated:
          type: integer
          description: Last modification timestamp for Resource Group.
          format: int64
      required:
        - slug
        - name
    CreateResourceGroupRequest:
      title: Create Resource Group Request
      x-stoplight:
        id: z8g6ol73nsqjs
      type: object
      description: Create Resource Group request
      x-examples:
        resource-group-request:
          slug: example_resource_group
          name: Example_Resource Group
          color: '#0063F7'
          tags:
            example-tag-1: example-tag-1-value
            example-tag-2: example-tag-2-value
          description: This is an Example Resource Group
          included_scope:
            - filter: EXCLUDING_CHILD_SCOPES
              account: sample_account
              org: sample_organization
              project: sample_project
          resource_filter:
            - resource_type: resource
              identifiers:
                - example_resource
              attribute_name: resource_attribute
              attribute_values:
                - example_resource_attribute
          include_all: false
      properties:
        slug:
          type: string
          minLength: 1
          maxLength: 64
          pattern: '^[a-zA-Z_][0-9a-zA-Z_$]{0,63}$'
          description: Resource Group identifier
        name:
          type: string
          minLength: 1
          maxLength: 64
          pattern: '^[a-zA-Z_][0-9a-zA-Z-_ ]{0,63}$'
          description: Resource Group name
        color:
          type: string
          description: Color associated with the Resource Group.
        tags:
          type: object
          additionalProperties:
            type: string
          maxProperties: 128
          description: Resource Group tags
        description:
          type: string
          maxLength: 1024
          description: Resource Group description
        included_scope:
          $ref: '#/components/schemas/ResourceGroupScope'
        resource_filter:
          $ref: '#/components/schemas/ResourceFilter'
        include_all:
          type: boolean
          description: Boolean value for including all resources in Resource Group.
      required:
        - slug
        - name
    ResourceGroupScope:
      title: Resource Group Scope
      x-stoplight:
        id: w8j3bc9323bxb
      type: object
      description: Included Scope levels for this Resource Group
      x-examples:
        example-1:
          filter: EXCLUDING_CHILD_SCOPES
          account: sample_account
          org: sample_organization
          project: sample_project
      properties:
        filter:
          type: string
          enum:
            - EXCLUDING_CHILD_SCOPES
            - INCLUDING_CHILD_SCOPES
          description: Including or Excluding Child scopes.
        account:
          type: string
          description: Account identifier
        org:
          type: string
          description: Organization identifier
        project:
          type: string
          description: Project identifier
    ResourceFilter:
      title: Resource Filter
      x-stoplight:
        id: m5qhp13hm6o1z
      type: object
      description: Specifies resources in Resource Group.
      properties:
        resource_type:
          type: string
          description: Specifies the type of Resource.
        identifiers:
          type: array
          description: Identifiers for the Resource Type.
          items:
            type: string
        attribute_name:
          type: string
          description: Attribute name on the basis of which filtering will be done.
        attribute_values:
          type: array
          description: Attribute values selected
          items:
            type: string
      required:
        - resource_type
      x-examples:
        example-resource-filter:
          resource_type: resource
          identifiers:
            - example_resource
          attribute_name: resource_attribute
          attribute_values:
            - example_resource_attribute
    ResourceSelectorFilter:
      title: ResourceSelectorFilter
      x-stoplight:
        id: e9w76jvt3g2gs
      type: object
      description: Filter object for Resource
      properties:
        resource_type:
          type: string
          description: Type of Resource
        resource_slug:
          type: string
          description: Resource identifier
      required:
        - resource_type
      x-examples:
        example-resource-filter:
          resource_type: resource
          resource_slug: example_resource
  securitySchemes:
    x-api-key:
      name: x-api-key
      type: apiKey
      in: header
  parameters:
    AccountParam:
      name: account
      in: query
      required: false
      schema:
        type: string
      description: 'Slug field of the account the resource is scoped to. This is required for Authorization methods other than the x-api-key header. If you are using the x-api-key header, this can be skipped.'
    Limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        default: 30
        maximum: 100
      description: 'Pagination: Number of items to return.'
    PageIndex:
      name: page
      in: query
      required: false
      schema:
        type: integer
        default: 0
      description: 'Pagination page number strategy: Specify the page number within the paginated collection related to the number of items on each page.'
    SearchTerm:
      name: search_term
      in: query
      required: false
      schema:
        type: string
      description: This would be used to filter resources having attributes matching the search term.
    OrgParam:
      name: org
      in: path
      required: true
      schema:
        type: string
      description: Organization identifier
    ProjectParam:
      name: project
      in: path
      required: true
      schema:
        type: string
      description: Project identifier
    ResourceGroupParam:
      name: resource-group
      in: path
      required: true
      schema:
        type: string
      description: Resource Group identifier
    IdentifierFilter:
      name: identifier_filter
      in: query
      required: false
      schema:
        type: array
        uniqueItems: true
        items:
          type: string
      description: Filter by Identifiers
    ResourceListFilter:
      name: resource_list_filter
      in: query
      required: false
      schema:
        type: array
        uniqueItems: true
        items:
          $ref: '#/components/schemas/ResourceSelectorFilter'
      description: Filter by particular Resource
    ManagedFilter:
      name: managed_filter
      in: query
      required: false
      schema:
        type: string
        enum:
          - NO_FILTER
          - ONLY_MANAGED
          - ONLY_CUSTOM
      description: Filter by Harness Managed
  responses:
    ResourceGroupsListResponse:
      description: Resource Groups List Response
      content:
        application/json:
          schema:
            type: array
            description: List of Resource Groups
            items:
              $ref: '#/components/schemas/ResourceGroupsResponse'
          examples:
            resource-group-list-response:
              value:
                - slug: example_resource_group
                  name: Example_Resource Group
                  color: '#0063F7'
                  tags:
                    example-tag-1: example-tag-1-value
                    example-tag-2: example-tag-2-value
                  description: This is an Example Resource Group
                  allowed_scope_levels:
                    - account
                  included_scope:
                    - filter: EXCLUDING_CHILD_SCOPES
                      account: sample_account
                      org: sample_organization
                      project: sample_project
                  resource_filter:
                    - resource_type: resource
                      identifiers:
                        - example_resource
                      attribute_name: resource_attribute
                      attribute_values:
                        - example_resource_attribute
                  include_all: false
                  harness_managed: true
                  created: 1234567890
                  updated: 1234567890
      headers:
        Link:
          schema:
            type: string
          description: 'Links to related resources, in the format defined by [RFC 5988](https://tools.ietf.org/html/rfc5988#section-5). This will include a link with relation type `next` to the next page, if there is a next page.'
    ResourceGroupsResponse:
      description: Resource Group Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResourceGroupsResponse'
          examples:
            resource-group-response:
              value:
                slug: example_resource_group
                name: Example_Resource Group
                color: '#0063F7'
                tags:
                  example-tag-1: example-tag-1-value
                  example-tag-2: example-tag-2-value
                description: This is an Example Resource Group
                allowed_scope_levels:
                  - account
                included_scope:
                  - filter: EXCLUDING_CHILD_SCOPES
                    account: sample_account
                    org: sample_organization
                    project: sample_project
                resource_filter:
                  - resource_type: resource
                    identifiers:
                      - example_resource
                    attribute_name: resource_attribute
                    attribute_values:
                      - example_resource_attribute
                include_all: false
                harness_managed: true
                created: 1234567890
                updated: 1234567890
  requestBodies:
    CreateResourceGroupRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateResourceGroupRequest'
          examples:
            resource-group-request:
              value:
                slug: example_resource_group
                name: Example_Resource Group
                color: '#0063F7'
                tags:
                  example-tag-1: example-tag-1-value
                  example-tag-2: example-tag-2-value
                description: This is an Example Resource Group
                included_scope:
                  - filter: EXCLUDING_CHILD_SCOPES
                    account: sample_account
                    org: sample_organization
                    project: sample_project
                resource_filter:
                  - resource_type: resource
                    identifiers:
                      - example_resource
                    attribute_name: resource_attribute
                    attribute_values:
                      - example_resource_attribute
                include_all: false
      description: Create Resource Group request body